### ISSUE TITLE
"Are you connected to the internet?" Message popped up while attempting to sign-up

### ISSUE THREAD

**Issue by HernyDavis100** [Tho100/FlowStorage#1]
There's an issue when I filled all the required forms I got an messagebox saying "Are you conneted to the internet?" after pressing Sign Up button. My internet connection is just fine, why is this happening?

**Comment by Tho100** [comment]
Hello Davis, apparently this is temporary server shortage meaning our server is currently down for a moment, try to sign up again for another couple of hours. If the problem still persists try to see for an update for our application on Microsoft Store.
